#!/usr/bin/env bash

search=$1
#if no search term is specified, print usage and exit
if [ ! $search ]
	then
		echo "usage: $0 <cmd to search process list for>"
		exit
fi
ps aux | grep -v grep | grep -v ami | grep -i $search
