#!/usr/bin/env perl
use warnings;
use strict;
my @lines=();
$lines[0]=shift;
if(!-t STDIN){@lines=<>;}
if(!$lines[0])
{
	print "usage: $0 <portnum>\n";
	exit();
}

foreach my $port(@lines)
{
	my $rets=`/usr/sbin/lsof -i:$port | grep LISTEN`;chomp($rets);
	my $pid=(split(/\s+/,$rets))[1];
	print "killing $pid\n";
	`kill $pid`;
}
