#!/bin/bash 
#with a slight modification for my preferences

SLEEP=10
ITER=-1
usage () 
{
	echo "Usage: $0 [options] \"cmd to run\"
	-n (val)  number of iterations
	-t (val)  seconds to sleep between
	-f (filename) loop over each thing in the file - use \$1 as the replacement
	-g (filename2) second file to loop over, use \$2 as the replacement"
}
while getopts "t:n:f:g:h?" opt; do
	case $opt in
		n)
			ITER="$OPTARG"
			;;
		t)
			SLEEP="$OPTARG"
			;;
		f)
			FILE="$OPTARG"
			;;
		g)
			FILEF="$OPTARG"
			;;
		h)
			usage
			exit
			;;
		?)
			usage
			exit
			;;
	esac
done
shift $(($OPTIND - 1))

CMD=$1

if [[ $FILE ]]
then
	for line in $(cat $FILE)
	do
		cmd_tmp=$CMD
		cmd_tmp=${cmd_tmp/\$1/$line}
		if [[ $FILEF ]]
		then
			for linef in $(cat $FILEF)
			do
				cmd_tmp_two=$cmd_tmp
				cmd_tmp_two=${cmd_tmp_two/\$2/$linef}
				sh -c "$cmd_tmp_two"
			done
		else
			sh -c "$cmd_tmp"
		fi
	done
	exit
fi

#check for no command to be run passed
if [[ -z "$CMD" ]]
then
	usage
	exit
fi

#loop, escaping if it reaches max iter
for (( i=1; ; i++ ))
do
	$CMD
	if ( (($ITER > 0)) && (($i >= $ITER))  )
	then
		break
	fi
	sleep $SLEEP
done
