#!/bin/bash 
#via: http://thdonline.wordpress.com/2009/03/14/shell-script-to-generate-random-password/
#with a slight modification for my preferences

CHAR_ARRAY=( {a..z} {A..Z} {0..9}  \! \@ \# \$ \% \^ \& \* \( \) \[ \] \{ \} \: \; \, \. \< \> \?)

while getopts "n" opt; do
	case $opt in
		n)
			CHAR_ARRAY=( {a..z} {A..Z} {0..9} )
			;;
	esac
done
shift $(($OPTIND - 1))

MAXSIZE=$1

if [ "$MAXSIZE" != "" -a "$MAXSIZE" == "${MAXSIZE//[^0-9]/}" ]
then
#I don't like the extra output
	MAXSIZE=$MAXSIZE
else
	MAXSIZE=16
fi


MODNUM=${#CHAR_ARRAY[*]} 
for index in `shuf --input-range=0-$(( ${#CHAR_ARRAY[*]} - 1 )) | head -${MAXSIZE}`
do
	echo -n "${CHAR_ARRAY[$index]}"
done
echo ""
